### ISSUE TITLE
App Wrongly Says Pick is Duplicate When New Pick Entered

### ISSUE THREAD

**Issue by mattheworres** [mattheworres/phpdraft#12]
Saw this probably half a dozen times as I did an offline draft last night - but as the commish is entering one pick, some sort of race condition occurs where I'm entering an undrafted player for Pick n, and as it's spinning (suggesting its entering the nth pick) the modal dialog pops up for duplicate pick entry as if we tried to enter the same player for the next pick (pick #n+1).

**Comment by mattheworres** [comment]
Since it happens during the selection of a player through the autocomplete, I'd have to believe that the select event is being fired erroneously somehow while the current pick is being loaded from the server. I will add an extra condition into that handler to make sure we're not executing during that time, but this is a really hard one to reproduce. Will close it for now and will re-open if anyone else sees it happening.

**Comment by zo0o0ot** [comment]
I'm drafting tonight, any reason why I should worry about this?
I'm going to plan on this not being a problem, but if it is one, I'll let you know.
