### ISSUE TITLE
Question: Can users be linked to teams/managers

### ISSUE THREAD

**Issue by zo0o0ot** [mattheworres/phpdraft#14]
I'm trying to understand the use case of a draft that isn't done in person.  Should I be giving out the commish password to let everyone log in as me at the same time for draft picks, or can users be assigned to teams, and draft only on behalf of that team?

**Comment by mattheworres** [comment]
@zo0o0ot the standard usecase that PHPDraft is designed for is this one:

There is one commissioner, and several managers. A commissioner owns a draft, and the draft has several managers. There is no official direct link between a PHPDraft "manager" and the real life "manager". The commissioner is intended to be the person entering the picks for the draft. When folks are remote, they have to notify the commissioner somehow (outside of PHPDraft at the moment) of their intended pick.

For offline drafts that have everyone present, I've suggested in the past to log in as the commissioner, then leave the laptop running on a "podium" so each manager goes up when it's their turn and enters their pick.

I entered a feature suggestion on the project's Feathub page that may help ease this pain, in which non-logged in (anonymous) users who have access to the draft (if there's a draft password, they've provided it) can open a dialog box and suggest a pick, which would pop up on the "Add Pick" screen for that draft's commissioner. Clicking on a suggestion would auto-fill the pick, and then the Commish would then just need to hit "Add Pick" to enter it. See the feature here to vote/provide feedback if you wish: http://feathub.com/mattheworres/phpdraft/+7

**Comment by mattheworres** [comment]
@zo0o0ot I would also suggest to run a few tests before doing a live draft using the model where several remote managers are all logged in as the commissioner - to lock in scope during 2.0 development I purposefully did not make the app robust in the area of concurrent commissioners. You may end up seeing some odd situations on the Add Pick screen as I don't think it currently polls the API listening for updates to the draft (as the assumption is that there's only 1 active Add Pick screen in use).
