### ISSUE TITLE
Edit Pick doesn't work for last pick of round - undo last pick?

### ISSUE THREAD

**Issue by zo0o0ot** [mattheworres/phpdraft#15]
I attempted to edit a pick during a draft last night, but because it was the last pick of the round and the draft had started the next round, I couldn't figure out how to edit the pick.  This was a serpentine draft, so the next person picking was the same person, but I still couldn't get it to revert back to the previous pick.  Perhaps an "admin undo most recent pick" function is in order?

**Comment by mattheworres** [comment]
@zo0o0ot I'll consider doing an undo button in the future, for sure, but at the moment if you go to the Commish Toolbox -> Edit Pick then cycle to the round the pick was in, then select the last pick in order to edit it -- does that do what you need it to?

**Comment by zo0o0ot** [comment]
Ah, it could have been user error.  I didn't know how to select a round outside of the current round.

**Comment by mattheworres** [comment]
I'll consider finding a way to make that UX experience more obvious. It's apparent to me, but I'm the one who wrote everything :)

Suggestions always welcome. Thanks!

**Comment by zo0o0ot** [comment]
I went and did a test draft, and I found the next and previous buttons this time.  They were light colored and faded into the background.  I didn't see them when I didn't know that they were there, but I see them know that I'm expecting them.  Maybe a darker color would make them easier to notice?
