### ISSUE TITLE
phpdraft.com - player search on NFLE league

### ISSUE THREAD

**Issue by xylopolist** [mattheworres/phpdraft#19]
Hello Matthew,

Planning on doing some drafts this weekend, and the new web app is really stunning - great work! Just one issue, when using the extended NFL rosters and trying to enter picks, the auto search feature is not working for me - any way you could correct that? Thanks again and have a great weekend!

**Comment by mattheworres** [comment]
I'll certainly look into this and see why. I know shortly after I released 2.0 I found some bugs around NFLE leagues that I had initially missed, but I will get on this immediately and figure it out.

**Comment by mattheworres** [comment]
@xylopolist take a gander now. When I updated the players the other day it must've wiped out all of the extended rosters in the system... Weird. Re-uploaded and it seems to be working now. Please let me know if you find anything else!

**Comment by xylopolist** [comment]
Rock n' Roll!
