### ISSUE TITLE
Chrome/Opera (any OS) creates SPDY protocol errors on depth chart

### ISSUE THREAD

**Issue by mattheworres** [mattheworres/phpdraft#22]
This is OS independent (I've seen it on both Windows and OSX) and is on the latest version of Chrome. I can confirm it is not an issue with any plugins I have installed either, because a clean copy of Chrome produces the same issue.

The browser won't send the XHR requests to update the depth chart when a player is dragged to a new depth chart position. The request has a status of `(failed)`, and the console gets an error message: `PUT https://www.phpdraft.com/api/draft/59/pick/5026/depth_chart/37 net::ERR_SPDY_PROTOCOL_ERROR`

This issue has been observed to also occur with the latest version of Opera, but not Firefox or Safari.

**Comment by mattheworres** [comment]
Created a Stackoverflow question for this issue: http://stackoverflow.com/questions/38986585/put-request-generates-spdy-protocol-errors-only-in-chrome-or-opera

**Comment by zo0o0ot** [comment]
Upvoted :+1:

**Comment by mattheworres** [comment]
So, my shared webhosting may be the culprit here. Looks like they have both SPDY and HTTP/2 protocols enabled on the server. SPDY is experimental and was deprecated once HTTP/2 came out, and in Chrome 51 they disabled support of it.

Webhost refuses to disable SPDY because they don't wish to disrupt their other customers, so I may be looking for alternate hosting (including Openshift).

**Comment by mattheworres** [comment]
Working on moving the site over to DigitalOcean this weekend in order to resolve this issue (should speed up the app 6x or more), but I will go ahead and close this issue.
