### ISSUE TITLE
Phpdraft.com Issue - trouble turning off depth chart / saving edits

### ISSUE THREAD

**Issue by xylopolist** [mattheworres/phpdraft#24]
Hello, having an issue with the phpdraft.com site: when trying to turn off depth charts I'm getting this message:

Unable to edit draft
An exception occurred while executing 'UPDATE draft SET commish_id = ?, draft_name = ?, draft_sport = ?, draft_style = ?, draft_password = ?, draft_rounds = ?, using_depth_charts = ? WHERE draft_id = ?': SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'using_depth_charts' at row 1

Also having an issue with saving any edits to the draft. Perhaps you could look into it when you get a chance? Thanks for all of your support and for the great draft utility. :) 

David

**Comment by mattheworres** [comment]
Yikes! That's a bug indeed. I'll get on fixing that! Thanks for the heads up.

**Comment by mattheworres** [comment]
Fixed! Translating `bool`s from the front end to MySQL always proves a bit of a stupid pain sometimes, but I got this one sewn up. Chalk up another instance where unit tests would have likely saved me from doing this after the fact :)

PHPDraft.com has been patched, I should have a patch release that includes this fix in it later this week.
