### ISSUE TITLE
Add Deployer Deployment Support

### ISSUE THREAD

**Issue by mattheworres** [mattheworres/phpdraft#28]
It would be a nice to have to add in Deployer ( https://deployer.org/ ) support to help automate the build & push of the app.

Where I'd like this to go is to require new installers to install Deployer and possibly a DB tool via Composer, and to use both of those to stand up the database and web servers respectively.

**Comment by zo0o0ot** [comment]
This sounds pretty cool.  Anything to ease the process of first-time creation and updating existing setups would be nice.
