### ISSUE TITLE
Create a Vagrant box to make development easier

### ISSUE THREAD

**Issue by mattheworres** [mattheworres/phpdraft#34]
Getting the requisite software installed can be a hassle and also muck up one's local machine. Using software like Vagrant can make this way easier.

Setup and share a Vagrant box that other contributors can use to more easily contribute to the project.

**Comment by zo0o0ot** [comment]
This sounds cool.  I used to do dev work out of a vagrant box, so this would be a bunch easier for me to deal with.

**Comment by mattheworres** [comment]
I may consider using Docker instead, as Vagrant relies on whatever virtualization software you provide (VirtualBox, VMWare, etc) to spin up a full virtual machine. Docker seems to be a little more lightweight.

Still, I don't have a great idea what this looks like - I want something that allows me to use a local editor (VSCode, Sublime, etc.) installed on my local machine, and I can just pull in a [Docker/Vagrant] box to run PHP, MySQL, Node, Yarn etc. for me without having to clutter up my machine with those dependencies/installations.
