### ISSUE TITLE
phpdraft.com error

### ISSUE THREAD

**Issue by xylopolist** [mattheworres/phpdraft#35]
Is phpdraft.com still active and supported? Having an issue creating a new draft for 2017.. see the below screenshot for the error when creating a league. Thanks!

![image](https://cloud.githubusercontent.com/assets/2117224/26482126/203fcc30-41ab-11e7-9be2-b85babdf0e86.png)

**Comment by mattheworres** [comment]
Ack! Looks like you found an odd bug. I feel like I may or may not have fixed this in a newer version... But I'll take a look to see if I can get it updated. Sorry about that!

**Comment by mattheworres** [comment]
Ugh, so this should be fixed on phpdraft.com.

I have a few changes waiting in the wing that will require me to update some documentation first before pushing an update, it mainly has to do with the new deployment stuff I added in in the last 6 months. So there's no commit for this right now in the code, but it should be up soon. Ish.
