### ISSUE TITLE
Routing errors

### ISSUE THREAD

**Issue by btweedy** [mattheworres/phpdraft#36]
I am getting routing errors on every POST.  Below is an example of the errors I am getting in the debug logs

Issue fixed

**Comment by btweedy** [comment]
I will add I got the same errors when using the 2.1.0 and 2.1.1 Hotfixes 1 hotfixes

**Comment by btweedy** [comment]
Fixed it!

In the install it says to comment out lines 9 and 10 of .htaccess if you arent using SSL.  However, it should be lines 14 and 15.

**Comment by mattheworres** [comment]
Interesting. I'll try to keep this in mind with the next release, I've streamlined installs and updates in the development version and will try to keep the htaccess/web.config stuff with it.

Also an aside, if at all possible you should really look into Letsencrypt or similar services to leverage SSL for your websites. Is free, and it's way safer for everyone :)

**Comment by btweedy** [comment]
Thanks for the input on SSL.  I will look into it.  But, I am just using it solely for a draft board in a live draft so its not as important to get the SSL.  I will be the only one using it :)

**Comment by mattheworres** [comment]
Good good. Thanks for using the software, I hope I can incorporate your feedback and make the next version even better (once I finally get some more time to work on this project! :) )
