### ISSUE TITLE
Update Changelog.md with information about v2.2

### ISSUE THREAD

**Issue by zo0o0ot** [mattheworres/phpdraft#37]

**Comment by mattheworres** [comment]
This is definitely on the docket. Haven't had the time to push an official build on this, but the README, INSTALL and UPGRADE files all need updated with the new stuff. Hoping to get a good bit of development done on this in the winter months!

**Comment by mattheworres** [comment]
Please see https://github.com/mattheworres/phpdraft/wiki/Changelog !
