### ISSUE TITLE
initialize.sql script in "wrong" location

### ISSUE THREAD

**Issue by zo0o0ot** [mattheworres/phpdraft#5]
The initialize.sql script is located in `/api/Domain/Migrations/initialize.sql`, not `/api/Domain/Migrations/2.0.0/initialize.sql`.  I assume that updating the install docs are the best way to fix that, but I haven't successfully installed phpdraft yet, so I'm not sure.

**Comment by mattheworres** [comment]
Yep! A mistake indeed. Initialize is updated every time a new version comes out, but shouldn't be in a version-specific migration folder, so being at the root of Migrations makes sense.

This is one piece I wish there was better, stronger tooling around maintaining database schemas through source control. Rails has migrations baked in, and WebAPI has SSDT to lean on, but it's kind of the wild west everywhere else.

**Comment by mattheworres** [comment]
Thanks for the heads up. I fixed this in INSTALL.md
