### ISSUE TITLE
Ncaa Basketball player list

### ISSUE THREAD

**Issue by goose2288** [mattheworres/phpdraft#55]
Just wondering if your scraper could make a player list for the NCAA Mens Basketball rosters?  I do a draft every year for the March Madness Tournament.  Thanks

**Comment by mattheworres** [comment]
I can see about adding in NCAA Mens basketball, I'd have to go through and create a list of teams though.

Do you just need the CSV data? If so, I'd say go ahead and create this issue on https://github.com/mattheworres/hootdraft-scraper/issues and I can (pretty easily) add an option for `ncaam` that hands you back the data you're looking for.

If you were looking to get NCAAM into Hoot Draft so you can run a draft board with it, I can do that too, it'll just take a tiny bit longer to do it in both places.

**Comment by goose2288** [comment]
Yes!  just the CSV data is all I need.

**Comment by mattheworres** [comment]
So far I have 175 teams listed, but still need to define... 185 of them? Thus far I have over 2,800 players scraped.

**Comment by mattheworres** [comment]
362 teams in total, resulting in 5821 players scraped. I'll be honest, most of the team abbreviations were a best guess, and there are probably a few overlaps, but this should be pretty close:
[ncaam_players.txt](https://github.com/mattheworres/phpdraft/files/2863326/ncaam_players.txt)

**Comment by goose2288** [comment]
Absolutely awesome!!  Thanks so much!!
