### ISSUE TITLE
command prompt error

### ISSUE THREAD

**Issue by goose2288** [mattheworres/phpdraft#56]
Im trying to install the 2.3 version but I get the following error in command prompt after navigating to the  dir with the index.html file and typing vendor/bin/dep setup 

error
'vendor' is not recognized as an internal or external command 

thanks for any help

**Comment by mattheworres** [comment]
Try './vendor/bin/deposit setup'.

Also, that's the output of 'php --version' and 'composer --version' ?

**Comment by goose2288** [comment]
still no luck..I will try  version 2.2.0 and see how that goes.  Thanks

![hoot](https://user-images.githubusercontent.com/47576761/52918331-505c2500-32bb-11e9-9c36-eceedbfcc30b.jpg)

**Comment by mattheworres** [comment]
Can you provide the output of these two commands:

`php --version`
`composer --version`

I'll have to pop into my Windows box real quick, it's been a while since I have attempted an installation or deployment from a Windows machine, so that may be causing slight differences required in the instructions, too.

**Comment by goose2288** [comment]
ok sorry for delay.  here is what i got with those commands


PHP 5.6.40 (cli) (built: Jan  9 2019 15:12:01)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies



Composer version 1.8.4 2019-02-11 10:52:10

Usage:
  command [options] [arguments]

Options:
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
      --profile                  Display timing and memory usage information
      --no-plugins               Whether to disable plugins.
  -d, --working-dir=WORKING-DIR  If specified, use the given directory as workin
g directory.
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for norma
l output, 2 for more verbose output and 3 for debug

Available commands:
  about                Shows the short information about Composer.
  archive              Creates an archive of this composer package.
  browse               Opens the package's repository URL or homepage in your br
owser.
  check-platform-reqs  Check that platform requirements are satisfied.
  clear-cache          Clears composer's internal package cache.
  clearcache           Clears composer's internal package cache.
  config               Sets config options.
  create-project       Creates new project from a package into given directory.
  depends              Shows which packages cause the given package to be instal
led.
  diagnose             Diagnoses the system to identify common errors.
  dump-autoload        Dumps the autoloader.
  dumpautoload         Dumps the autoloader.
  exec                 Executes a vendored binary/script.
  global               Allows running commands in the global composer dir ($COMP
OSER_HOME).
  help                 Displays help for a command
  home                 Opens the package's repository URL or homepage in your br
owser.
  i                    Installs the project dependencies from the composer.lock
file if present, or falls back on the composer.json.
  info                 Shows information about packages.
  init                 Creates a basic composer.json file in current directory.
  install              Installs the project dependencies from the composer.lock
file if present, or falls back on the composer.json.
  licenses             Shows information about licenses of dependencies.
  list                 Lists commands
  outdated             Shows a list of installed packages that have updates avai
lable, including their latest version.
  prohibits            Shows which packages prevent the given package from being
 installed.
  remove               Removes a package from the require or require-dev.
  require              Adds required packages to your composer.json and installs
 them.
  run-script           Runs the scripts defined in composer.json.
  search               Searches for packages.
  self-update          Updates composer.phar to the latest version.
  selfupdate           Updates composer.phar to the latest version.
  show                 Shows information about packages.
  status               Shows a list of locally modified packages, for packages i
nstalled from source.
  suggests             Shows package suggestions.
  u                    Upgrades your dependencies to the latest version accordin
g to composer.json, and updates the composer.lock file.
  update               Upgrades your dependencies to the latest version accordin
g to composer.json, and updates the composer.lock file.
  upgrade              Upgrades your dependencies to the latest version accordin
g to composer.json, and updates the composer.lock file.
  validate             Validates a composer.json and composer.lock.
  why                  Shows which packages cause the given package to be instal
led.
  why-not              Shows which packages prevent the given package from being
 installed.

**Comment by mattheworres** [comment]
So, my apologies for not getting back to you sooner -- but looks like this is an issue with how I package the project. (I also haven't formally tested or "supported" doing any of this on Windows until now - it's all been just theoretically possible but I just haven't taken the time to do it).

Unfortunately it looks like support for the deployment tool I utilize is sketchy on Windows, and I wasn't able to find a way to get it to work myself.

Luckily, if you still have the webserver/database running, you can still manually deploy it as you would previously. The files in the release ZIP are ready-to-go and there are Apache and Nginx configuration examples to help you get started if you would still like to run your own install.

**Comment by mattheworres** [comment]
If you'd like to continue to chat about it, feel free to head over to the Gitter chat room here: https://gitter.im/mattheworres/phpdraft?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge I'd be happy to help you get your own version setup and running. Of course, you're always welcome to use the free version I have up and running at phpdraft.com , too!

**Comment by goose2288** [comment]
Ok no problem. Thanks for the help Matt!
