### ISSUE TITLE
Invalid security certificate for hootdraft.com?

### ISSUE THREAD

**Issue by zo0o0ot** [mattheworres/phpdraft#57]
Hey.  When I follow the link from github, I get a security certificate error.

```
hootdraft.com uses an invalid security certificate. The certificate is only valid for the following names: phpdraft.com, www.phpdraft.com Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

When I type in hootdraft.com by myself, I don't get the error.  I'm not sure why only one would have the exception.

**Comment by mattheworres** [comment]
Erm... Yeah. I hit that myself a bit ago. I need to buckle down and
actually make the domain switch, right now I just have the server
forwarding requests which is why it's complaining at you.

**Comment by zo0o0ot** [comment]
That makes sense. My version of the site is in shambles, so I can't throw shade your way.

**Comment by mattheworres** [comment]
Ok, got the domain switched over, made sure all the keys work and the email server is properly up and running, should be a go. Thanks for letting me know!
