### ISSUE TITLE
Draft- Custom league - Players with no first names - "Enter Pick" disabled.

### ISSUE THREAD

**Issue by zo0o0ot** [mattheworres/phpdraft#8]
![enterpick-disabled](https://cloud.githubusercontent.com/assets/876146/12939007/531d7c72-cf80-11e5-9af5-f5479558905e.png)

I was able to create my own league and enter players.  However, when trying to draft, the "enter pick" button is disabled by angular.  Up to this point, I've only edited `DraftDataRepository.php` - I was able to follow the convention and add position colors, positions, teams, and add their references to the `GetTeams` and `GetPositions` methods.

Once I got the correct CSV format, I got all the way up to the point of drafting, but the "Enter Pick" button is disabled.

It looks like the method preventing me from picking is an angular or coffeescript method:  `ng-disabled="commishPickEditCtrl.formIsInvalid()"`

I'll keep looking, but this validation fail surprised me.  It looks like I'll have to take a look at that in order to accomplish what I want to do.

**Comment by zo0o0ot** [comment]
I'm looking at `commish_pick_edit.coffee` and maybe this is a problem of my own invention.  I'm adding Schools as "players" and they don't exactly have first and last names, so I concatenated a comma at the end of the school name in order for the player information to be entered properly.  However, I think that the JS validation is failing because the "player" first name is either blank, empty, or missing.

**Comment by zo0o0ot** [comment]
Yep, the missing first name is the issue.  I manually added a first name to one of the "players", and it passed validation and allowed me to draft.  I may be able to update my dataset in order to get around this restriction.

**Comment by zo0o0ot** [comment]
Do you want me to make some documentation about how to create leagues?

**Comment by mattheworres** [comment]
That might be helpful. The way I get around this for the NFL, for instance, where entire teams are drafted (and Super Rugby, where teams are also drafted) is that their city is the first name, and then their team name is the second. So "New England" + "Patriots", "Pittsburgh" + "Steelers", "Minnesota" + "Vikings" so on and so forth. May make sense to put it in the DEVELOPMENT readme.

**Comment by mattheworres** [comment]
I'm going to mark this as a "wontfix" as that validation was intentional on my part, but feel free to continue your informal research on the Gitter chat channel (and continue entering bugs as you find them, for sure): https://gitter.im/mattheworres/phpdraft?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
